services:
  backend:
    container_name: backend
    build : .
    command: python manage.py runserver 0.0.0.0:8000
    volumes:
      - ./core:/app
    ports:
      - "8000:8000"
    environment:
      - SECRET_KEY= test
      - DEBUG= True
    depends_on:
      - redis

  worker:
    build: .
    command: celery -A core worker --loglevel=info
    volumes:
      - ./core:/app
    depends_on:
      - redis
      - backend

  redis:
    container_name: redis
    restart: always
    image: redis
    ports:
      - "6379:6379"
    command: redis-server --save 60 1 --loglevel warning

  smtp4dev:
    image: rnwood/smtp4dev:v3
    restart: always
    ports: 
      - '5000:80'
      - '25:25'
      - '143:143'
    volumes:
        - smtp4dev-data:/smtp4dev
    environment:
      - ServerOptions__HostName=smtp4dev

      
volumes:
  smtp4dev-data:
